/**
 * @author Toru Nagashima
 * See LICENSE file in root directory for full license.
 */
import fs from 'fs'
import path from 'path'
import { CLIEngine } from 'eslint'

const targetFile = path.resolve(__dirname, '../lib/rules.js')

fs.writeFileSync(
  targetFile,
  `/**
 * DON'T EDIT THIS FILE WHICH WAS GENERATED BY './scripts/generate-rules.js'.
 */
export default {
${fs
    .readdirSync(path.resolve(__dirname, '../lib/rules'))
    .map(fileName => path.basename(fileName, '.js'))
    .map(id => `        "${id}": require("./rules/${id}"),`)
    .join('\n')}
    }
`
)

const linter = new CLIEngine({ fix: true })
const result = linter.executeOnFiles([targetFile])
CLIEngine.outputFixes(result)
